#!/usr/bin/env bash
# Brand kit — one name, logo and accent colour pushed into every app that can
# take it, so the stack looks like one product. Sourced by stackctl (brand apply).
# Reads BRAND_NAME, BRAND_COLOR, BRAND_LOGO_URL from .env; the default logo is
# brand/logo.svg, served publicly by the console at /brand/logo.svg.
# Best-effort like provision.sh: a failure prints the manual fallback and continues.

brand_name()  { envval BRAND_NAME; }
brand_color() { envval BRAND_COLOR; }
brand_logo()  { local u; u="$(envval BRAND_LOGO_URL)"; [ -n "$u" ] && echo "$u" || echo "https://console.$(base_domain)/brand/logo.svg"; }
LOGO_FILE="$ROOT/brand/logo.svg"

# ---------- Hub (Homepage): title + accent via custom.css ----------
brand_homepage() {
  local cfg="$ROOT/apps/homepage/config"
  sed -i "s|^title:.*|title: $(brand_name)|" "$cfg/settings.yaml"
  cat > "$cfg/custom.css" <<EOF
/* generated by: stackctl brand apply */
:root { --brand: $(brand_color); }
#information-widgets, .service-card:hover, .bookmark:hover { border-color: var(--brand) !important; }
.service-title, h2, .information-widget-resource .text-theme-800 { color: var(--brand) !important; }
a:hover { color: var(--brand) !important; }
EOF
  app_running homepage && compose homepage restart >/dev/null 2>&1
  note_ok homepage "Hub — title + accent applied"
}

# ---------- Authentik: brand title, logo, CSS accent ----------
brand_authentik() {
  app_running authentik || return
  local base="https://auth.$(base_domain)/api/v3" tok uuid
  tok="$(envval AUTHENTIK_BOOTSTRAP_TOKEN)"
  # the API can lag a few seconds behind the container turning healthy; retry briefly
  local try; for try in 1 2 3 4 5 6; do
    uuid="$(http GET "$base/core/brands/" -H "Authorization: Bearer $tok" | sed -n 's/.*"brand_uuid":"\([^"]*\)".*/\1/p' | head -1)"
    [ -n "$uuid" ] && break; sleep 5
  done
  [ -n "$uuid" ] || { note_fail authentik "could not read brand (HTTP $HTTP_CODE)"; return; }
  http PATCH "$base/core/brands/$uuid/" -H "Authorization: Bearer $tok" -H "Content-Type: application/json" \
    -d "{\"branding_title\":\"$(json_escape "$(brand_name)")\",\"branding_logo\":\"$(json_escape "$(brand_logo)")\",\"branding_custom_css\":\":root{--pf-global--primary-color--100:$(brand_color);--pf-global--link--Color:$(brand_color);--pf-global--active-color--100:$(brand_color)}\"}" >/dev/null \
    && note_ok authentik "Sign-on — title, logo, accent applied" \
    || note_fail authentik "brand update failed (HTTP $HTTP_CODE)"
}

# ---------- Nextcloud: theming app via occ ----------
brand_nextcloud() {
  app_running nextcloud || return
  local c=fs-nextcloud-app-1
  docker exec -u www-data $c php occ theming:config name "$(brand_name)" >/dev/null 2>&1 &&
  docker exec -u www-data $c php occ theming:config color "$(brand_color)" >/dev/null 2>&1 &&
  docker exec -u www-data $c php occ theming:config url "https://home.$(base_domain)" >/dev/null 2>&1 || { note_fail nextcloud "occ theming failed"; return; }
  if [ -f "$LOGO_FILE" ]; then
    docker cp "$LOGO_FILE" $c:/tmp/brand-logo.svg >/dev/null 2>&1 && docker exec $c chown www-data /tmp/brand-logo.svg &&
    docker exec -u www-data $c php occ theming:config logo /tmp/brand-logo.svg >/dev/null 2>&1
  fi
  note_ok nextcloud "Files — name, colour, logo applied"
}

# ---------- Mattermost: site name + custom brand text ----------
brand_mattermost() {
  app_running mattermost || return
  local c=fs-mattermost-app-1
  docker exec $c mmctl --local config set TeamSettings.SiteName "$(brand_name)" >/dev/null 2>&1 &&
  docker exec $c mmctl --local config set TeamSettings.EnableCustomBrand true >/dev/null 2>&1 &&
  docker exec $c mmctl --local config set TeamSettings.CustomBrandText "Welcome to $(brand_name)" >/dev/null 2>&1 &&
  docker exec $c mmctl --local config set TeamSettings.CustomDescriptionText "$(brand_name) team chat" >/dev/null 2>&1 \
    && note_ok mattermost "Team chat — site name + brand text applied" \
    || note_fail mattermost "mmctl config set failed"
}

# ---------- Rocket.Chat: site name, logo asset, CSS accent ----------
brand_rocketchat() {
  app_running rocketchat || return
  local base="https://chat.$(base_domain)/api/v1" body tok uid
  body="$(http POST "$base/login" -H "Content-Type: application/json" \
    -d "{\"user\":\"$(json_escape "$(envval ADMIN_USER)")\",\"password\":\"$(json_escape "$(envval ADMIN_PASSWORD)")\"}")" || { note_fail rocketchat "admin login failed"; return; }
  tok="$(printf '%s' "$body" | sed -n 's/.*"authToken":"\([^"]*\)".*/\1/p')"; uid="$(printf '%s' "$body" | sed -n 's/.*"userId":"\([^"]*\)".*/\1/p')"
  # settings changes require the admin to re-prove identity (2FA-by-password headers)
  local sha; sha="$(printf '%s' "$(envval ADMIN_PASSWORD)" | sha256sum | cut -d' ' -f1)"
  local auth=(-H "X-Auth-Token: $tok" -H "X-User-Id: $uid" -H "x-2fa-method: password" -H "x-2fa-code: $sha")
  http POST "$base/settings/Site_Name" "${auth[@]}" -H "Content-Type: application/json" -d "{\"value\":\"$(json_escape "$(brand_name)")\"}" >/dev/null || { note_fail rocketchat "settings update failed (HTTP $HTTP_CODE)"; return; }
  http POST "$base/settings/Layout_Home_Title" "${auth[@]}" -H "Content-Type: application/json" -d "{\"value\":\"Welcome to $(json_escape "$(brand_name)")\"}" >/dev/null
  http POST "$base/settings/theme-custom-css" "${auth[@]}" -H "Content-Type: application/json" \
    -d "{\"value\":\":root{--rcx-color-button-background-primary-default:$(brand_color);--rcx-color-button-background-primary-hover:$(brand_color);--rcx-color-stroke-highlight:$(brand_color)}\"}" >/dev/null
  [ -f "$LOGO_FILE" ] && http POST "$base/assets.setAsset" "${auth[@]}" -F "assetName=logo" -F "asset=@$LOGO_FILE;type=image/svg+xml" >/dev/null
  note_ok rocketchat "Team chat — name, logo, accent applied"
}

# ---------- Chatwoot: installation config ----------
brand_chatwoot() {
  app_running chatwoot || return
  local out
  out="$(docker exec fs-chatwoot-rails-1 bundle exec rails runner "
{'BRAND_NAME'=>'$(brand_name)','LOGO'=>'$(brand_logo)','LOGO_THUMBNAIL'=>'$(brand_logo)','LOGO_DARK'=>'$(brand_logo)','BRAND_URL'=>'https://home.$(base_domain)','WIDGET_BRAND_URL'=>'https://home.$(base_domain)','INSTALLATION_NAME'=>'$(brand_name)'}.each{|k,v| InstallationConfig.find_or_initialize_by(name:k).update!(value:v)}; GlobalConfig.clear_cache; puts 'BRAND_OK'" 2>/dev/null)"
  printf '%s' "$out" | grep -q BRAND_OK && note_ok chatwoot "Support desk — brand name, logo applied" || note_fail chatwoot "rails runner failed"
}

# ---------- Listmonk: site name, logo, admin custom CSS ----------
brand_listmonk() {
  app_running listmonk || return
  local base="https://newsletter.$(base_domain)" jar cur
  jar="$(mktemp)"
  listmonk_session "$jar" || { rm -f "$jar"; note_fail listmonk "admin login failed"; return; }
  cur="$(http GET "$base/api/settings" -b "$jar")"
  cur="$(printf '%s' "$cur" | python3 -c "
import json,sys
d=json.load(sys.stdin)['data']
d['app.site_name']='$(brand_name)'; d['app.logo_url']='$(brand_logo)'; d['app.favicon_url']='$(brand_logo)'
d['appearance.admin.custom_css']=':root{--primary:$(brand_color);--primary-dark:$(brand_color)} .button.is-primary,a.button.is-primary{background:$(brand_color)!important;border-color:$(brand_color)!important}'
print(json.dumps(d))")"
  http PUT "$base/api/settings" -b "$jar" -H "Content-Type: application/json" -d "$cur" >/dev/null \
    && note_ok listmonk "Newsletter — name, logo, accent applied (app restarts itself)" \
    || note_fail listmonk "settings update failed (HTTP $HTTP_CODE)"
  rm -f "$jar"
}

# ---------- Easy!Appointments: company name ----------
brand_easyappointments() {
  app_running easyappointments || return
  http PUT "https://cal.$(base_domain)/index.php/api/v1/settings/company_name" -u "$(envval ADMIN_USER):$(envval ADMIN_PASSWORD)" \
    -H "Content-Type: application/json" -d "{\"value\":\"$(json_escape "$(brand_name)")\"}" >/dev/null \
    && note_ok easyappointments "Booking calendar — company name applied" \
    || note_fail easyappointments "settings update failed (HTTP $HTTP_CODE)"
}

# ---------- Ghost: title, accent, logo (needs SMTP: admin login emails a notice) ----------
brand_ghost() {
  app_running ghost || return
  [ -n "$(envval SMTP_HOST)" ] || { note_manual ghost "no SMTP — set title/accent in Ghost admin → Design"; return; }
  local base="https://blog.$(base_domain)/ghost/api/admin" jar
  jar="$(mktemp)"
  http POST "$base/session/" -c "$jar" -H "Content-Type: application/json" -H "Origin: https://blog.$(base_domain)" \
    -d "{\"username\":\"$(json_escape "$(envval ADMIN_EMAIL)")\",\"password\":\"$(json_escape "$(envval ADMIN_PASSWORD)")\"}" >/dev/null || { rm -f "$jar"; note_fail ghost "admin login failed"; return; }
  http PUT "$base/settings/" -b "$jar" -H "Content-Type: application/json" -H "Origin: https://blog.$(base_domain)" \
    -d "{\"settings\":[{\"key\":\"title\",\"value\":\"$(json_escape "$(brand_name)")\"},{\"key\":\"accent_color\",\"value\":\"$(brand_color)\"},{\"key\":\"logo\",\"value\":\"$(json_escape "$(brand_logo)")\"}]}" >/dev/null \
    && note_ok ghost "Blog — title, accent, logo applied" || note_fail ghost "settings update failed (HTTP $HTTP_CODE)"
  rm -f "$jar"
}

# Default logo: a monogram in the brand colour, regenerated on every apply
# unless the user dropped in their own brand/logo.svg (no "generated" marker).
brand_default_logo() {
  [ -z "$(envval BRAND_LOGO_URL)" ] || return 0
  if [ -f "$LOGO_FILE" ] && ! grep -q 'founder-stack:generated' "$LOGO_FILE"; then return 0; fi
  local initial; initial="$(printf '%s' "$(brand_name)" | cut -c1 | tr '[:lower:]' '[:upper:]')"
  cat > "$LOGO_FILE" <<LOGOEOF
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128"><!-- founder-stack:generated -->
  <rect width="128" height="128" rx="28" fill="$(brand_color)"/>
  <text x="64" y="86" text-anchor="middle" font-family="system-ui,-apple-system,Segoe UI,Roboto,sans-serif" font-weight="700" font-size="72" fill="#fff">${initial:-F}</text>
</svg>
LOGOEOF
  note_ok logo "Logo — monogram '$initial' in $(brand_color) (replace brand/logo.svg with your own any time)"
}

brand_apply() {
  PROVISION_OK=(); PROVISION_FAILED=(); PROVISION_MANUAL=()
  echo "Brand: $(brand_name)  colour: $(brand_color)  logo: $(brand_logo)"
  brand_default_logo
  brand_homepage; brand_authentik; brand_nextcloud; brand_mattermost; brand_rocketchat
  brand_chatwoot; brand_listmonk; brand_easyappointments; brand_ghost
  echo
  echo "The console picks the brand up automatically. Tasks, Analytics, Status page, Signatures, Forms, Passwords"
  echo "and Automations have no branding surface and keep their own look; CRM, Docs and Invoices take a logo in"
  echo "their own settings."
  if [ ${#PROVISION_MANUAL[@]} -gt 0 ]; then echo "Manual:"; printf '  - %s\n' "${PROVISION_MANUAL[@]}"; fi
}
